
#line 3 "lex.rwla.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 1
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE rwlarestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via rwlarestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void rwlarestart (FILE *input_file ,yyscan_t yyscanner );
void rwla_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE rwla_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void rwla_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void rwla_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void rwlapush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void rwlapop_buffer_state (yyscan_t yyscanner );

static void rwlaensure_buffer_stack (yyscan_t yyscanner );
static void rwla_load_buffer_state (yyscan_t yyscanner );
static void rwla_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER rwla_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE rwla_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE rwla_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE rwla_scan_bytes (yyconst char *bytes,int len ,yyscan_t yyscanner );

void *rwlaalloc (yy_size_t ,yyscan_t yyscanner );
void *rwlarealloc (void *,yy_size_t ,yyscan_t yyscanner );
void rwlafree (void * ,yyscan_t yyscanner );

#define yy_new_buffer rwla_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        rwlaensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            rwla_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        rwlaensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            rwla_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yynoreturn yy_fatal_error (yyconst char* msg ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 59
#define YY_END_OF_BUFFER 60
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[416] =
    {   0,
        0,    0,   60,   58,   52,   58,   49,   58,   58,   58,
       56,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   58,
        0,   42,    0,   49,    0,    0,    0,   40,   41,   55,
       56,    0,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   50,
        0,    0,    0,    0,   55,    0,    0,   53,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,

       57,   57,   57,   57,   57,   57,   57,   51,    0,    0,
        0,    0,   54,   57,   57,   57,   57,   57,   57,   37,
       57,   57,   57,   57,   57,   36,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,    0,   57,
       57,   38,    0,    0,    0,   57,   33,   57,   57,   21,
       31,   57,   57,   57,   57,   57,   57,   57,   20,   57,
        0,   34,   57,   24,   57,   57,   57,   57,    0,    0,
        0,   57,   57,    0,    0,    0,    0,    0,   57,   57,
       57,   57,   19,   57,   35,   57,   57,   57,   30,    0,
       57,   25,   26,   57,   28,    0,    0,    0,   57,   29,

        0,    0,    0,    0,    0,   57,   23,   57,   57,    0,
       32,   57,   57,   57,    0,   22,   57,    0,    0,    0,
       57,    0,    0,    0,    0,    0,   57,   57,    0,    0,
        0,    0,    0,    0,    0,   57,    0,   57,    0,   57,
        0,   10,    0,   39,    0,    0,    0,    0,    0,   57,
       57,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       57,    0,   57,    0,   27,    0,    0,    0,    0,    0,
        0,    0,   57,    0,    4,    0,    0,    0,    0,    0,
        0,    0,    0,   57,    0,    0,    8,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   13,    0,    0,

        0,    0,    0,   12,   57,    0,    0,    0,    0,    0,
        0,    0,    0,   45,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   57,    5,    0,    0,    0,    0,
       48,   43,   46,   47,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   48,   43,    0,
       46,    0,   47,    0,    0,    0,    0,   17,    0,   16,
        0,   18,    0,    0,    0,    9,    0,   44,    0,    0,
        0,    0,   14,    0,    0,    0,    0,    7,   11,   44,
        0,   46,    0,   47,    0,    0,    0,   15,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    6,

        0,    0,    0,    0,    2,    0,    0,    0,    0,    0,
        0,    3,    0,    1,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    7,    1,    1,    1,    1,
        1,    8,    9,    1,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,    1,    1,
       15,    1,    1,    1,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
        1,   42,    1,    1,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,   63,   64,   65,   66,   67,
       68,   69,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[70] =
    {   0,
        1,    2,    3,    2,    1,    1,    1,    1,    1,    4,
        1,    1,    5,    6,    7,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    9,    5,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10
    } ;

static yyconst flex_uint16_t yy_base[430] =
    {   0,
        0,    0,  895,  896,  896,   65,    0,   27,  884,  885,
       61,   56,   53,   64,   69,   37,   50,   45,    0,   55,
       56,   67,   58,   59,   76,  111,   65,   69,   86,  129,
       94,  896,    0,    0,  837,  833,  828,  896,  896,  121,
      124,  130,    0,   91,   94,  126,  111,  127,  126,  122,
      122,  131,  134,  119,  124,  125,  142,  144,  128,  145,
      131,  149,  133,  138,  131,  170,  135,  164,  150,  896,
      886,  822,  830,  838,  187,  199,  871,  861,  163,  178,
      174,  172,  180,  182,  183,  186,  200,  190,  198,  203,
      189,  194,  188,  194,  204,  201,  206,  195,  214,  221,

      209,  220,  221,  258,  214,  237,  231,  896,  814,  807,
      787,  834,  831,  228,  225,  223,  248,  235,  243,    0,
      253,  239,  259,  241,  243,    0,  262,  256,  245,  250,
      285,  264,  271,  272,  265,  269,  265,  279,  311,  281,
      274,    0,  774,  779,  268,  286,    0,  276,  298,    0,
        0,  299,  311,  299,  313,  300,  311,  319,    0,  304,
      338,    0,  319,    0,  327,  328,  319,  316,  322,  323,
      321,  339,  338,  773,  771,  781,  768,  760,  331,  346,
      352,  334,  385,  350,    0,  348,  355,  369,    0,  374,
      356,    0,    0,  368,    0,  366,  372,  384,  367,    0,

      767,  757,  762,  744,  753,  368,    0,  369,  405,  431,
        0,  392,  412,  393,  400,    0,  392,  388,  405,  397,
      409,  740,  743,  722,  728,  716,  416,  417,  438,  407,
      428,  422,  414,  443,  427,  427,  479,  437,  442,  435,
      438,  896,  443,    0,  715,  719,  762,  717,  728,  445,
      505,  456,  463,  456,  482,  512,  482,  472,  479,  480,
      496,  490,  520,  498,    0,  486,  509,  725,  715,  766,
      711,  716,  530,  533,  896,  508,  513,  508,  540,  522,
      531,  528,  531,  517,  539,  556,  896,  540,  543,  752,
      751,  759,  749,  745,  560,  530,  531,  896,  552,  550,

      555,  552,  552,  896,  561,  553,  569,  571,  564,  555,
      743,    0,  750,  896,    0,    0,  572,  581,  580,  572,
      575,  585,  589,  591,  619,  896,  577,  600,  595,  602,
      740,  735,  735,  732,  587,  593,  599,  590,  604,  617,
      602,  608,  640,  631,  621,  614,  620,  732,  729,    0,
      729,  675,  632,  450,  658,  627,  624,  896,  647,  896,
      631,  896,  632,  651,  650,  896,  642,    0,  443,  419,
      680,  638,  896,  655,  665,  670,  671,  896,  896,    0,
      400,  896,  311,  896,  672,  654,  670,  896,  658,  660,
      668,  679,  702,  683,  689,  694,  693,  724,  678,  896,

      697,  686,  688,  704,  896,  705,  702,  714,  713,  700,
      712,  896,  707,  896,  896,  782,  792,  798,  808,   69,
      811,  814,  821,  828,  835,  845,  855,  865,  875
    } ;

static yyconst flex_int16_t yy_def[430] =
    {   0,
      415,    1,  415,  415,  415,  416,  417,  415,  415,  415,
      415,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  415,
      416,  415,  416,  417,  415,  415,  415,  415,  415,  415,
      415,  415,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,

      418,  418,  418,  418,  418,  418,  418,  415,  415,  415,
      415,  415,  415,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  415,  418,
      418,  418,  415,  415,  415,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      415,  418,  418,  418,  418,  418,  418,  418,  415,  415,
      415,  418,  418,  415,  415,  415,  415,  415,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  415,
      418,  418,  418,  418,  418,  415,  415,  415,  418,  418,

      415,  415,  415,  415,  415,  418,  418,  418,  418,  415,
      418,  418,  418,  418,  415,  418,  418,  415,  415,  415,
      418,  415,  415,  415,  415,  415,  418,  418,  415,  415,
      415,  415,  415,  415,  415,  418,  415,  418,  415,  418,
      415,  415,  415,  418,  415,  415,  415,  415,  415,  418,
      418,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      418,  415,  418,  415,  418,  415,  415,  415,  415,  415,
      415,  415,  418,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  418,  415,  415,  415,  415,  415,  415,
      415,  419,  415,  415,  415,  415,  415,  415,  415,  415,

      415,  415,  415,  415,  418,  415,  415,  415,  415,  415,
      415,  420,  419,  415,  421,  422,  415,  415,  415,  415,
      415,  415,  415,  415,  418,  415,  415,  415,  415,  415,
      415,  423,  424,  425,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  423,  426,
      424,  415,  425,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  427,  428,  429,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  427,
      428,  415,  429,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  210,  415,  415,

      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,    0,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415
    } ;

static yyconst flex_uint16_t yy_nxt[966] =
    {   0,
        4,    4,    5,    4,    6,    7,    8,    4,    4,    9,
        4,   10,   11,    4,    4,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   19,   19,   21,   22,   23,   19,
       24,   19,   25,   26,   27,   28,   19,   29,   19,   19,
       19,   30,   19,   12,   13,   14,   15,   16,   17,   18,
       19,   20,   19,   19,   21,   22,   23,   19,   24,   19,
       25,   26,   27,   28,   19,   29,   19,   19,   19,   32,
       35,   40,   49,   41,   44,   56,   57,   58,  332,   50,
       42,   36,   45,   59,   46,   60,   61,   62,   53,   47,
       37,   48,   54,   51,   63,   64,   52,   67,   32,   68,

       49,   55,   44,   56,   57,   58,   33,   50,   42,   69,
       45,   59,   46,   60,   61,   62,   53,   47,   79,   48,
       54,   51,   63,   64,   52,   67,   65,   68,   80,   55,
       66,   70,   71,   75,   40,   33,   41,   69,   77,   77,
       76,   81,   78,   42,   82,   83,   79,   84,   85,   86,
       87,   88,   90,   91,   65,   92,   80,   93,   66,   94,
       89,   95,   96,   97,   98,   99,  100,  102,   76,   81,
      105,   42,   82,   83,  101,   84,   85,   86,   87,   88,
       90,   91,  106,   92,  107,   93,  114,   94,   89,   95,
       96,   97,   98,   99,  100,  102,  103,  115,  105,   75,

      116,  117,  101,  118,  104,  119,   76,  112,  112,  120,
      106,  113,  107,  121,  114,  122,  123,  124,  125,  126,
      127,  128,  129,  130,  103,  115,  131,  132,  116,  117,
      133,  118,  104,  119,   76,  134,  135,  120,  136,  137,
      138,  121,  140,  122,  123,  124,  125,  126,  127,  128,
      129,  130,  141,  142,  131,  132,  146,  147,  133,  139,
      139,  139,  148,  134,  135,  149,  136,  137,  138,  150,
      140,  151,  152,  153,  154,  155,  156,  157,  158,  159,
      141,  142,  160,  162,  146,  147,  161,  161,  161,  163,
      148,  164,  165,  149,  166,  167,  168,  150,  172,  151,

      152,  153,  154,  155,  156,  157,  158,  159,  173,  179,
      160,  162,  139,  139,  139,  384,  180,  163,  176,  164,
      165,  181,  166,  167,  168,  177,  172,  182,  169,  178,
      183,  184,  185,  186,  187,  188,  173,  179,  189,  161,
      161,  161,  191,  170,  180,  171,  192,  193,  194,  181,
      195,  196,  197,  198,  199,  182,  169,  200,  183,  184,
      185,  186,  187,  188,  206,  207,  189,  208,  209,  211,
      191,  170,  190,  171,  192,  193,  194,  212,  195,  196,
      197,  198,  199,  213,  214,  200,  210,  210,  210,  215,
      216,  217,  206,  207,  218,  208,  209,  211,  219,  220,

      190,  221,  227,  228,  382,  212,  229,  229,  229,  236,
      238,  213,  214,  237,  237,  237,  239,  215,  216,  217,
      240,  241,  218,  384,  242,  243,  219,  220,  244,  221,
      227,  228,  210,  210,  210,  250,  251,  236,  238,  229,
      229,  229,  253,  254,  239,  255,  256,  382,  240,  241,
      261,  230,  242,  243,  370,  231,  244,  232,  257,  259,
      233,  234,  263,  250,  251,  235,  260,  252,  264,  265,
      253,  254,  266,  255,  256,  258,  267,  273,  261,  230,
      237,  237,  237,  231,  275,  232,  257,  259,  233,  234,
      263,  276,  277,  235,  260,  252,  264,  265,  278,  280,

      266,  281,  282,  258,  267,  273,  274,  274,  274,  262,
      283,  284,  275,  279,  279,  279,  285,  287,  288,  276,
      277,  286,  286,  286,  289,  297,  278,  280,  298,  281,
      282,  295,  295,  295,  274,  274,  274,  262,  283,  284,
      299,  279,  279,  279,  285,  287,  288,  301,  302,  303,
      304,  305,  289,  297,  306,  309,  298,  286,  286,  286,
      310,  295,  295,  295,  318,  319,  296,  320,  299,  321,
      322,  323,  300,  324,  307,  301,  302,  303,  304,  305,
      325,  326,  306,  309,  327,  317,  328,  329,  310,  330,
      308,  335,  318,  319,  296,  320,  336,  321,  322,  323,

      300,  324,  307,  337,  338,  339,  340,  341,  325,  326,
      342,  344,  327,  317,  328,  329,  345,  330,  308,  335,
      343,  343,  343,  346,  336,  347,  355,  356,  357,  358,
      359,  337,  338,  339,  340,  341,  360,  361,  342,  344,
      362,  343,  343,  343,  345,  354,  364,  365,  366,  367,
      372,  346,  373,  347,  355,  356,  357,  358,  359,  371,
      371,  371,  374,  375,  360,  361,  376,  377,  362,  378,
      379,  386,  387,  363,  364,  365,  366,  367,  372,  369,
      373,  371,  371,  371,  388,  389,  390,  391,  392,  393,
      374,  375,  394,  395,  376,  377,  396,  378,  379,  386,

      387,  363,  397,  398,  398,  398,  399,  385,  400,  401,
      402,  403,  388,  389,  390,  391,  392,  393,  404,  405,
      394,  395,  406,  407,  396,  398,  398,  398,  408,  409,
      397,  410,  411,  412,  399,  385,  400,  401,  402,  403,
      413,  414,  352,  350,  348,  354,  404,  405,  352,  350,
      406,  407,  348,  415,  314,  331,  408,  409,  316,  410,
      411,  412,  315,  314,  312,  311,  294,  293,  413,  414,
      292,  291,  290,  272,  271,  270,  269,  268,  249,  248,
      247,  415,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   34,   34,  246,   34,   34,   34,   34,   34,

       34,   34,   43,  245,  226,   43,  225,   43,  313,  313,
      313,  313,  313,  313,  313,  313,  224,  313,  333,  223,
      333,  334,  222,  334,  349,  205,  204,  349,  203,  202,
      349,  351,  351,  351,  201,  351,  175,  351,  353,  353,
      353,  174,  353,  113,  353,  368,  113,  145,  368,  368,
      368,  368,  368,  368,  368,  380,  144,  143,  380,  380,
      380,  380,  380,  380,  380,  381,  381,  381,  381,  381,
      381,  381,  381,   78,  381,  383,  383,  383,  383,  383,
      383,  383,  383,   78,  383,  111,  110,  109,  108,   74,
       73,   72,   39,   38,  415,    3,  415,  415,  415,  415,

      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415
    } ;

static yyconst flex_int16_t yy_chk[966] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    6,
        8,   11,   13,   11,   12,   16,   17,   18,  420,   14,
       11,    8,   12,   20,   12,   21,   22,   23,   15,   12,
        8,   12,   15,   14,   24,   25,   14,   27,   31,   28,

       13,   15,   12,   16,   17,   18,    6,   14,   11,   29,
       12,   20,   12,   21,   22,   23,   15,   12,   44,   12,
       15,   14,   24,   25,   14,   27,   26,   28,   45,   15,
       26,   30,   30,   40,   41,   31,   41,   29,   42,   42,
       40,   46,   42,   41,   47,   48,   44,   49,   50,   51,
       52,   53,   54,   55,   26,   56,   45,   57,   26,   58,
       53,   59,   60,   61,   62,   63,   64,   65,   40,   46,
       67,   41,   47,   48,   64,   49,   50,   51,   52,   53,
       54,   55,   68,   56,   69,   57,   79,   58,   53,   59,
       60,   61,   62,   63,   64,   65,   66,   80,   67,   75,

       81,   82,   64,   83,   66,   84,   75,   76,   76,   85,
       68,   76,   69,   86,   79,   87,   88,   89,   90,   91,
       92,   93,   94,   95,   66,   80,   96,   97,   81,   82,
       98,   83,   66,   84,   75,   99,  100,   85,  101,  102,
      103,   86,  105,   87,   88,   89,   90,   91,   92,   93,
       94,   95,  106,  107,   96,   97,  114,  115,   98,  104,
      104,  104,  116,   99,  100,  117,  101,  102,  103,  118,
      105,  119,  121,  122,  123,  124,  125,  127,  128,  129,
      106,  107,  130,  132,  114,  115,  131,  131,  131,  133,
      116,  134,  135,  117,  136,  137,  138,  118,  140,  119,

      121,  122,  123,  124,  125,  127,  128,  129,  141,  146,
      130,  132,  139,  139,  139,  383,  148,  133,  145,  134,
      135,  149,  136,  137,  138,  145,  140,  152,  139,  145,
      153,  154,  155,  156,  157,  158,  141,  146,  160,  161,
      161,  161,  163,  139,  148,  139,  165,  166,  167,  149,
      168,  169,  170,  171,  172,  152,  139,  173,  153,  154,
      155,  156,  157,  158,  179,  180,  160,  181,  182,  184,
      163,  139,  161,  139,  165,  166,  167,  186,  168,  169,
      170,  171,  172,  187,  188,  173,  183,  183,  183,  190,
      191,  194,  179,  180,  196,  181,  182,  184,  197,  198,

      161,  199,  206,  208,  381,  186,  209,  209,  209,  212,
      214,  187,  188,  213,  213,  213,  215,  190,  191,  194,
      217,  218,  196,  370,  219,  220,  197,  198,  221,  199,
      206,  208,  210,  210,  210,  227,  228,  212,  214,  229,
      229,  229,  230,  231,  215,  232,  233,  369,  217,  218,
      236,  210,  219,  220,  354,  210,  221,  210,  234,  235,
      210,  210,  238,  227,  228,  210,  235,  229,  239,  240,
      230,  231,  241,  232,  233,  234,  243,  250,  236,  210,
      237,  237,  237,  210,  252,  210,  234,  235,  210,  210,
      238,  253,  254,  210,  235,  229,  239,  240,  255,  257,

      241,  258,  259,  234,  243,  250,  251,  251,  251,  237,
      260,  261,  252,  256,  256,  256,  262,  264,  266,  253,
      254,  263,  263,  263,  267,  276,  255,  257,  277,  258,
      259,  273,  273,  273,  274,  274,  274,  237,  260,  261,
      278,  279,  279,  279,  262,  264,  266,  280,  281,  282,
      283,  284,  267,  276,  285,  288,  277,  286,  286,  286,
      289,  295,  295,  295,  296,  297,  274,  299,  278,  300,
      301,  302,  279,  303,  286,  280,  281,  282,  283,  284,
      305,  306,  285,  288,  307,  295,  308,  309,  289,  310,
      286,  317,  296,  297,  274,  299,  318,  300,  301,  302,

      279,  303,  286,  319,  320,  321,  322,  323,  305,  306,
      324,  327,  307,  295,  308,  309,  328,  310,  286,  317,
      325,  325,  325,  329,  318,  330,  335,  336,  337,  338,
      339,  319,  320,  321,  322,  323,  340,  341,  324,  327,
      342,  343,  343,  343,  328,  353,  344,  345,  346,  347,
      356,  329,  357,  330,  335,  336,  337,  338,  339,  355,
      355,  355,  359,  361,  340,  341,  363,  364,  342,  365,
      367,  372,  374,  343,  344,  345,  346,  347,  356,  352,
      357,  371,  371,  371,  375,  376,  377,  385,  386,  387,
      359,  361,  389,  390,  363,  364,  391,  365,  367,  372,

      374,  343,  392,  393,  393,  393,  394,  371,  395,  396,
      397,  399,  375,  376,  377,  385,  386,  387,  401,  402,
      389,  390,  403,  404,  391,  398,  398,  398,  406,  407,
      392,  408,  409,  410,  394,  371,  395,  396,  397,  399,
      411,  413,  351,  349,  348,  334,  401,  402,  333,  332,
      403,  404,  331,  398,  313,  311,  406,  407,  294,  408,
      409,  410,  293,  292,  291,  290,  272,  271,  411,  413,
      270,  269,  268,  249,  248,  247,  246,  245,  226,  225,
      224,  398,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  417,  417,  223,  417,  417,  417,  417,  417,

      417,  417,  418,  222,  205,  418,  204,  418,  419,  419,
      419,  419,  419,  419,  419,  419,  203,  419,  421,  202,
      421,  422,  201,  422,  423,  178,  177,  423,  176,  175,
      423,  424,  424,  424,  174,  424,  144,  424,  425,  425,
      425,  143,  425,  113,  425,  426,  112,  111,  426,  426,
      426,  426,  426,  426,  426,  427,  110,  109,  427,  427,
      427,  427,  427,  427,  427,  428,  428,  428,  428,  428,
      428,  428,  428,   78,  428,  429,  429,  429,  429,  429,
      429,  429,  429,   77,  429,   74,   73,   72,   71,   37,
       36,   35,   10,    9,    3,  415,  415,  415,  415,  415,

      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "rwlarglex.l"
/*
 * RWP*Load Simulator
 *
 * Copyright (c) 2023 Oracle Corporation
 * Licensed under the Universal Permissive License v 1.0
 * as shown at https://oss.oracle.com/licenses/upl/
 *
 * Real World performance Load simulator lexer/tokenizer
 * for various $option directives
 *
 * rwlarglex.l
 *
 * History
 *
 * bengsig  14-feb-2024 - yy* -> rwm->rwly*
 * bengsig  14-feb-2024 - Also \t in sql syntax
 * bengsig   6-feb-2024 - Own option processing
 * bengsig  30-jan-2024 - All includes in rwl.h
 * bengsig  12-jun-2023 - Make rwm a variable in scanners
 * bengsig  10-aug-2022 - Output userhelp in order from rwl source file
 * bengsig  10-aug-2022 - Don't reorder useroption/userswitch
 * bengsig  04-jul-2022 - Restructure scan string, scan SQL code
 * bengsig  28-jun-2022 - Generate project
 * bengsig  01-jun-2022 - create java scan
 * bengsig  17-may-2022 - "call" is SQL, not PL/SQL
 * bengsig  12-apr-2022 - Allow hyphen in useroption/userswitch
 * bengsig  30-mar-2022 - with is a sql keyword
 * bengsig  19-map-2022 - Add lex tag 
 * bengsig  20-sep-2021 - Include and igore scan for number constants and idetifiers
 * bengsig  16-jun-2021 - Include scan for string and sql to exclude option scan there
 * bengsig  18-feb-2021 - Use bison 3 syntax (which desupports 2)
 * bengsig  07-jul-2020 - Allow help text for $useroption and $userswitch
 * bengsig  06-jul-2020 - Make sure $longoption:quiet is used
 * bengsig  13-may-2020 - Creation
 */
#line 38 "rwlarglex.l"
#include "rwl.h"
// This lexer is never called from a scanner, but just
// to get some needed defines, we include output from rwldiprs.y:
#include "rwldiprs.tab.h"
#define YYSTYPE RWLZSTYPE
#define YY_DECL sb4 rwlalex(void *yylval_param, void * yyscanner)
#define YY_USER_ACTION \
{ rwm = (rwlaget_extra(yyscanner)); \
  rwm->loc.inpos += yyleng; \
  rwm->rwlyleng = (ub4) yyleng; \
  rwm->rwlytext = (text *)yytext; \
}


// to avoid flex generating some code:
// #define YY_NO_INPUT

// The following causes slightly changed
// scan for string constants and SQL
// via the includes below
#define RWL_IN_ARGLEX

#line 837 "lex.rwla.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#define YY_EXTRA_TYPE rwl_main *

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int rwlalex_init (yyscan_t* scanner);

int rwlalex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int rwlalex_destroy (yyscan_t yyscanner );

int rwlaget_debug (yyscan_t yyscanner );

void rwlaset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE rwlaget_extra (yyscan_t yyscanner );

void rwlaset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *rwlaget_in (yyscan_t yyscanner );

void rwlaset_in  (FILE * _in_str ,yyscan_t yyscanner );

FILE *rwlaget_out (yyscan_t yyscanner );

void rwlaset_out  (FILE * _out_str ,yyscan_t yyscanner );

			int rwlaget_leng (yyscan_t yyscanner );

char *rwlaget_text (yyscan_t yyscanner );

int rwlaget_lineno (yyscan_t yyscanner );

void rwlaset_lineno (int _line_number ,yyscan_t yyscanner );

int rwlaget_column  (yyscan_t yyscanner );

void rwlaset_column (int _column_no ,yyscan_t yyscanner );

YYSTYPE * rwlaget_lval (yyscan_t yyscanner );

void rwlaset_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int rwlawrap (yyscan_t yyscanner );
#else
extern int rwlawrap (yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int rwlalex \
               (YYSTYPE * yylval_param ,yyscan_t yyscanner);

#define YY_DECL int rwlalex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			rwlaensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				rwla_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		rwla_load_buffer_state(yyscanner );
		}

	{
#line 66 "rwlarglex.l"



  rwl_main *rwm = 0; // will be set using YY_USER_ACTION



#line 1118 "lex.rwla.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 416 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 896 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
#line 74 "rwlarglex.l"
case 2:
/* rule 2 can match eol */
#line 75 "rwlarglex.l"
case 3:
/* rule 3 can match eol */
#line 76 "rwlarglex.l"
case 4:
/* rule 4 can match eol */
#line 77 "rwlarglex.l"
case 5:
/* rule 5 can match eol */
#line 78 "rwlarglex.l"
case 6:
/* rule 6 can match eol */
#line 79 "rwlarglex.l"
case 7:
/* rule 7 can match eol */
#line 80 "rwlarglex.l"
case 8:
/* rule 8 can match eol */
#line 81 "rwlarglex.l"
case 9:
/* rule 9 can match eol */
#line 82 "rwlarglex.l"
case 10:
/* rule 10 can match eol */
#line 83 "rwlarglex.l"
case 11:
/* rule 11 can match eol */
#line 84 "rwlarglex.l"
case 12:
/* rule 12 can match eol */
#line 85 "rwlarglex.l"
case 13:
/* rule 13 can match eol */
#line 86 "rwlarglex.l"
case 14:
/* rule 14 can match eol */
#line 87 "rwlarglex.l"
case 15:
/* rule 15 can match eol */
#line 88 "rwlarglex.l"
case 16:
/* rule 16 can match eol */
#line 89 "rwlarglex.l"
case 17:
/* rule 17 can match eol */
#line 90 "rwlarglex.l"
case 18:
/* rule 18 can match eol */
#line 91 "rwlarglex.l"
case 19:
/* rule 19 can match eol */
#line 92 "rwlarglex.l"
case 20:
/* rule 20 can match eol */
#line 93 "rwlarglex.l"
case 21:
/* rule 21 can match eol */
#line 94 "rwlarglex.l"
case 22:
/* rule 22 can match eol */
#line 95 "rwlarglex.l"
case 23:
/* rule 23 can match eol */
#line 96 "rwlarglex.l"
case 24:
/* rule 24 can match eol */
#line 97 "rwlarglex.l"
case 25:
/* rule 25 can match eol */
#line 98 "rwlarglex.l"
case 26:
/* rule 26 can match eol */
#line 99 "rwlarglex.l"
case 27:
/* rule 27 can match eol */
#line 100 "rwlarglex.l"
case 28:
/* rule 28 can match eol */
#line 101 "rwlarglex.l"
case 29:
/* rule 29 can match eol */
#line 102 "rwlarglex.l"
case 30:
/* rule 30 can match eol */
#line 103 "rwlarglex.l"
case 31:
/* rule 31 can match eol */
#line 104 "rwlarglex.l"
case 32:
/* rule 32 can match eol */
#line 105 "rwlarglex.l"
case 33:
/* rule 33 can match eol */
#line 106 "rwlarglex.l"
case 34:
/* rule 34 can match eol */
#line 107 "rwlarglex.l"
case 35:
/* rule 35 can match eol */
#line 108 "rwlarglex.l"
case 36:
/* rule 36 can match eol */
#line 109 "rwlarglex.l"
case 37:
/* rule 37 can match eol */
#line 110 "rwlarglex.l"
case 38:
/* rule 38 can match eol */
#line 111 "rwlarglex.l"
case 39:
/* rule 39 can match eol */
#line 112 "rwlarglex.l"
case 40:
/* rule 40 can match eol */
#line 113 "rwlarglex.l"
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 113 "rwlarglex.l"
{
// vi tag: rwlscansql
#include "rwlscansql.c"
	}
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 118 "rwlarglex.l"
{ // 
			    // See comments in rwllexer.l
// vi tag: rwlscanstring
#include "rwlscanstring.c"
			  }
	YY_BREAK
/*LEXTAG:rwlalex*/
case 43:
#line 126 "rwlarglex.l"
case 44:
YY_RULE_SETUP
#line 126 "rwlarglex.l"
{
		  if (!bit(rwm->m2flags, RWL_P2_SCANFIRST))
		    rwlerror(rwm, RWL_ERROR_ARGUMENT_NOT_FIRST);
		  else
		  {
		    rwl_arglist *alp;
		    text *argnam =  rwm->rwlytext+12 ;

		    // need an early check for quiet
		    if (0 == rwlstrcmp(rwm->rwlytext+12, (text *) "quiet"))
		      bis(rwm->mflags, RWL_P_QUIET);

		    alp = rwlalloc(rwm, sizeof(rwl_arglist));
		    alp->argname = rwlalloc(rwm,rwlstrlen(argnam)+3); 
		    alp->helpseq = rwm->helpseq++;
		    rwlstrcpy(alp->argname,(text *)"--");
		    rwlstrcpy(alp->argname+2,argnam);
		    if (!rwm->lngargl) // the first
		    {
		      rwm->lngargl = alp;
		    }
		    else // add to list
		    {
		      alp->nextarg = rwm->lngargl;
		      rwm->lngargl = alp;
		    }
		  }
		}
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 155 "rwlarglex.l"
{
		  if (!bit(rwm->m2flags, RWL_P2_SCANFIRST))
		    rwlerror(rwm, RWL_ERROR_ARGUMENT_NOT_FIRST);
		  else
		  {
		    rwl_helplist *ph, *uh;
		    ub4 len;
		    ph = uh = rwm->helphead;
		    // find the last and append there
		    while (uh)
		    {
		      ph = uh;
		      uh = uh->nexthlp;
		    }
		    uh = rwlalloc(rwm, sizeof(rwl_helplist));
		    uh->helpseq = rwm->helpseq++;
		    uh->helptext = rwlstrdup(rwm, rwm->rwlytext+11);
		    len = rwlstrlen(uh->helptext);
		    if (len)
		      uh->helptext[len-1] = 0; // remove " 
		    if (ph)
		      ph->nexthlp = uh;
		    else
		      rwm->helphead = uh;
		  }

		}
	YY_BREAK
case 46:
/* rule 46 can match eol */
#line 185 "rwlarglex.l"
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 185 "rwlarglex.l"
{
		  if (!bit(rwm->m2flags, RWL_P2_SCANFIRST))
		    rwlerror(rwm, RWL_ERROR_ARGUMENT_NOT_FIRST);
		  else
		  {
		    // Check it isn't an ordinary long option
		    ub4 i;
		    ub1 argflag;
		    rwl_arglist *alp, *ale;
		    text *aa, *argnam, *hh, *arghelp;

		    argnam = arghelp = 0;

		    if ('s' == rwm->rwlytext[5])
		    {
		      argflag = RWL_USER_ARG_NOARG;
		      aa = rwm->rwlytext+ 12;
		    }
		    else
		    {
		      argflag = 0;
		      aa = rwm->rwlytext+ 12;
		    }
		    // is there helptext
		    hh = rwlstrchr(aa, ':');
		    if (hh)
		    {
		      // User has helptext as a string
		      argnam = rwlalloc(rwm, hh-aa+1);
		      rwlstrnncpy(argnam,aa,hh-aa+1);
		      /* Parfait_ALLOW memory-leak - It IS free'd in rwlmain.c */
		      arghelp = rwlstrdup(rwm, hh+2);
		      arghelp[rwlstrlen(arghelp)-1] = 0;
		    }
		    else
		    {
		      // Construct a help text
		      ub4 helplen;
		      argnam = rwlstrdup(rwm, aa);
		      if (argflag)
		      {
		        // --(no-)argname : unset or set argname
			helplen = 2*rwlstrlen(argnam) + sizeof("--(no-) : unset or set ") + 1;
			/* Parfait_ALLOW memory-leak - It IS free'd in rwlmain.c */
		        arghelp = rwlalloc(rwm, helplen);
			snprintf((char *)arghelp,helplen, "--(no-)%s : unset or set %s",argnam, argnam);
		      }
		      else
		      {
			// --argname : set value for argname
			helplen = 2*rwlstrlen(argnam) + sizeof("-- : set value for ") + 1;
			/* Parfait_ALLOW memory-leak - It IS free'd in rwlmain.c */
		        arghelp = rwlalloc(rwm, helplen);
			snprintf((char *)arghelp,helplen, "--%s : set value for %s",argnam, argnam);
		      }

		    }

		    // Make sure it isn't ordinary
		    for (i=0; i<rwloptcount-1; i++)
		    {
		      if (! rwlstrcmp(argnam, rwloptions[i].longn))
		      {
			rwlerror(rwm, RWL_ERROR_ARGUMENT_IS_ORDINARY, argnam);
			rwlfree(rwm, arghelp);
			goto cannotuseargument;
		      }
		    }
		    // Make sure it isn't repeated
		    ale = alp = rwm->usrargl;
		    while (alp)
		    {
		      if (! rwlstrcmp(argnam, alp->argname))
		      {
			rwlerror(rwm, RWL_ERROR_ARGUMENT_ALREADY, argnam);
			rwlfree(rwm, arghelp);
			goto cannotuseargument;
		      }
		      ale = alp;
		      alp = alp->nextarg;
		    }

		    alp = rwlalloc(rwm, sizeof(rwl_arglist));
		    alp->helpseq = rwm->helpseq++;
		    alp->argname = argnam;
		    alp->arghelp = arghelp;
		    alp->argflags = argflag;
		    if (!rwm->usrargl) // the first
		    {
		      rwm->usrargl = alp;
		    }
		    else // add to end of list
		    {
		      ale->nextarg = alp;
		    }
		    cannotuseargument:
		    ;
		  }
		}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 285 "rwlarglex.l"
{
			  rwlerrormute(rwm, (ub4) rwlatoi(rwm->rwlytext+12),1 /* warn if !warning*/ );
			  }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 290 "rwlarglex.l"
{ 
			  /* just make gcc shut up about unput not being used */
			  if (0)
			    unput(0);
			}
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 296 "rwlarglex.l"
{ rwm->loc.lineno++; }
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 297 "rwlarglex.l"
{ rwm->loc.lineno++; }
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 298 "rwlarglex.l"
{ rwm->loc.lineno++; }
	YY_BREAK
case 53:
#line 300 "rwlarglex.l"
case 54:
#line 301 "rwlarglex.l"
case 55:
#line 302 "rwlarglex.l"
case 56:
#line 303 "rwlarglex.l"
case 57:
YY_RULE_SETUP
#line 303 "rwlarglex.l"
{ ; /* ignore number constants and identifiers */ }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 304 "rwlarglex.l"
{ ; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 306 "rwlarglex.l"
ECHO;
	YY_BREAK
#line 1545 "lex.rwla.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * rwlalex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( rwlawrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of rwlalex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	yy_size_t number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					rwlarealloc((void *) b->yy_ch_buf,(yy_size_t) (b->yy_buf_size + 2) ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			rwlarestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) rwlarealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,(yy_size_t) new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 416 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 416 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
	yy_is_jam = (yy_current_state == 415);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp , yyscan_t yyscanner)
{
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = yyg->yy_n_chars + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					rwlarestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( rwlawrap(yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void rwlarestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        rwlaensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            rwla_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	rwla_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	rwla_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void rwla_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		rwlapop_buffer_state();
	 *		rwlapush_buffer_state(new_buffer);
     */
	rwlaensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	rwla_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (rwlawrap()) processing, but the only time this flag
	 * is looked at is after rwlawrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void rwla_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE rwla_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) rwlaalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in rwla_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) rwlaalloc((yy_size_t) (b->yy_buf_size + 2) ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in rwla_create_buffer()" );

	b->yy_is_our_buffer = 1;

	rwla_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with rwla_create_buffer()
 * @param yyscanner The scanner object.
 */
    void rwla_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		rwlafree((void *) b->yy_ch_buf ,yyscanner );

	rwlafree((void *) b ,yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a rwlarestart() or at EOF.
 */
    static void rwla_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	rwla_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then rwla_init_buffer was _probably_
     * called from rwlarestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void rwla_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		rwla_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void rwlapush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	rwlaensure_buffer_stack(yyscanner);

	/* This block is copied from rwla_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from rwla_switch_to_buffer. */
	rwla_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void rwlapop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	rwla_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		rwla_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void rwlaensure_buffer_stack (yyscan_t yyscanner)
{
	int num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)rwlaalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in rwlaensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)rwlarealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in rwlaensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE rwla_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) rwlaalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in rwla_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	rwla_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to rwlalex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       rwla_scan_bytes() instead.
 */
YY_BUFFER_STATE rwla_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return rwla_scan_bytes(yystr,(int) strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to rwlalex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE rwla_scan_bytes  (yyconst char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) rwlaalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in rwla_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = rwla_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in rwla_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE rwlaget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int rwlaget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int rwlaget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *rwlaget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *rwlaget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int rwlaget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *rwlaget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void rwlaset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void rwlaset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "rwlaset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void rwlaset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "rwlaset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see rwla_switch_to_buffer
 */
void rwlaset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void rwlaset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int rwlaget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void rwlaset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * rwlaget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void rwlaset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* rwlalex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int rwlalex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) rwlaalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* rwlalex_init_extra has the same functionality as rwlalex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to rwlaalloc in
 * the yyextra field.
 */

int rwlalex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    rwlaset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) rwlaalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    rwlaset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from rwlalex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * rwlalex_init()
     */
    return 0;
}

/* rwlalex_destroy is for both reentrant and non-reentrant scanners. */
int rwlalex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		rwla_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		rwlapop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	rwlafree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        rwlafree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * rwlalex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    rwlafree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *rwlaalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *rwlarealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void rwlafree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see rwlarealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 306 "rwlarglex.l"



#undef rwm /* now outside flex code */

/*LEXTAG:rwlawrap*/
sb4 rwlawrap(yyscan_t ys)
{
  return 1;
}

/* This routine depends on varous defines from flex, so it must be here */
/*LEXTAG:rwlascanstring*/
void rwlascanstring(rwl_main *rwm, const char *str)
{
  text *savinam;
  void *dummy;
  // https://stackoverflow.com/questions/780676/string-input-to-flex-lexer
  YY_BUFFER_STATE astate;

  // Something utterly wrong if we try this during execute
  if (!bit(rwm->mflags, RWL_P_ONLYMAINTH))
  {  
    rwlsevere(rwm, "[rwlaparsestring-noonlymain:%x]", rwm->mflags);
    return;
  }
  if (rwm->codename)
  {  
    rwlsevere(rwm, "[rwlaparsestring-incode:%s]", rwm->codename);
    return;
  }
  if (rwm->phead || rwm->ptail || rwm->skipdep)
  {  
    rwlsevere(rwm, "[rwlaparsestring-hasstack;0x%p;0x%p;%d]"
    , rwm->phead, rwm->ptail, rwm->skipdep);
    return;
  }
  savinam = rwm->inam;
  astate = rwla_scan_string(str, rwm->rwlascanner);
  rwlalex((union YYSTYPE *)&dummy, rwm->rwlascanner); // scan the string
  rwla_delete_buffer(astate, rwm->rwlascanner);

  rwm->inam = savinam;
}

rwlcomp(rwlarglex_l, RWL_GCCFLAGS)


